/**
 * Test runner for Nova Forge C++ server system tests.
 * Auto-generated from the monolithic test_systems.cpp split.
 */
#include <iostream>

// Global test counters
int testsRun = 0;
int testsPassed = 0;

// Forward declarations of per-file registration functions
void run_capacitor_system_tests();
void run_shield_recharge_system_tests();
void run_single_component_system_tests();
void run_state_machine_system_tests();
void run_weapon_system_tests();
void run_targeting_system_tests();
void run_ship_database_tests();
void run_wormhole_database_tests();
void run_wormhole_system_tests();
void run_fleet_system_tests();
void run_world_persistence_tests();
void run_movement_system_tests();
void run_logger_tests();
void run_server_metrics_tests();
void run_mission_system_tests();
void run_skill_system_tests();
void run_module_system_tests();
void run_inventory_system_tests();
void run_loot_system_tests();
void run_npc_database_tests();
void run_drone_system_tests();
void run_insurance_system_tests();
void run_bounty_system_tests();
void run_market_system_tests();
void run_corporation_system_tests();
void run_contract_system_tests();
void run_persistence_tests();
void run_pisystem_tests();
void run_manufacturing_system_tests();
void run_research_system_tests();
void run_chat_system_tests();
void run_character_creation_system_tests();
void run_tournament_system_tests();
void run_leaderboard_system_tests();
void run_station_system_tests();
void run_wreck_salvage_system_tests();
void run_server_console_tests();
void run_fleet_morale_system_tests();
void run_captain_personality_system_tests();
void run_fleet_chatter_system_tests();
void run_warp_anomaly_system_tests();
void run_captain_relationship_system_tests();
void run_emotional_arc_system_tests();
void run_fleet_cargo_system_tests();
void run_tactical_overlay_system_tests();
void run_combat_system_tests();
void run_ai_system_tests();
void run_warp_system_tests();
void run_mining_system_tests();
void run_ecs_components_tests();
void run_protocol_handler_tests();
void run_refining_system_tests();
void run_pcg_ship_generator_tests();
void run_fleet_formation_system_tests();
void run_captain_memory_system_tests();
void run_ship_fitting_system_tests();
void run_warp_cinematic_system_tests();
void run_anomaly_system_tests();
void run_scanner_system_tests();
void run_difficulty_scaling_system_tests();
void run_mission_template_system_tests();
void run_mission_generator_system_tests();
void run_reputation_system_tests();
void run_lod_system_tests();
void run_stress_test_tests();
void run_economy_tests();
void run_fleet_chatter_tests();
void run_captain_relationship_tests();
void run_rumor_propagation_tests();
void run_captain_personality_tests();
void run_persistence_stress_tests();
void run_spatial_hash_system_tests();
void run_compressed_persistence_tests();
void run_background_simulation_system_tests();
void run_npc_intent_system_tests();
void run_npc_behavior_tree_system_tests();
void run_combat_threat_system_tests();
void run_security_response_system_tests();
void run_ambient_traffic_system_tests();
void run_snapshot_replication_system_tests();
void run_interest_management_system_tests();
void run_pcg_framework_tests();
void run_character_mesh_cybernetics_tests();
void run_asteroid_field_generator_tests();
void run_anomaly_generator_tests();
void run_npc_encounter_generator_tests();
void run_warp_hudtravel_mode_tests();
void run_warp_auto_comfort_tests();
void run_warp_accessibility_tunnel_geometry_tests();
void run_phase_11_fleet_progression_system_tests();
void run_phase_11_fleet_cargo_ship_loss_tests();
void run_phase_11_station_deployment_system_tests();
void run_phase_11_fleet_warp_formation_system_tests();
void run_phase_11_fleet_civilization_tests();
void run_warp_meditation_system_tests();
void run_rumor_questline_system_tests();
void run_captain_departure_system_tests();
void run_captain_transfer_system_tests();
void run_npc_rerouting_system_tests();
void run_local_reputation_system_tests();
void run_station_news_system_tests();
void run_wreck_persistence_system_tests();
void run_fleet_history_system_tests();
void run_character_mesh_system_tests();
void run_rig_system_tests();
void run_turret_generator_tests();
void run_planet_generator_tests();
void run_habitat_generator_tests();
void run_grav_bike_tests();
void run_legend_system_tests();
void run_ancient_tech_tests();
void run_docking_system_tests();
void run_survival_system_tests();
void run_menu_system_tests();
void run_crew_system_tests();
void run_salvage_exploration_tests();
void run_interior_exterior_coupling_tests();
void run_race_and_lore_tests();
void run_market_order_tests();
void run_spine_hull_generator_tests();
void run_terrain_generator_tests();
void run_turret_placement_system_tests();
void run_damage_state_generator_tests();
void run_procedural_texture_generator_tests();
void run_economy_driven_generator_tests();
void run_ai_economic_actor_system_tests();
void run_turret_ai_system_tests();
void run_expanded_ship_class_tests();
void run_star_system_generator_tests();
void run_galaxy_generator_tests();
void run_alliance_system_tests();
void run_sovereignty_system_tests();
void run_war_declaration_system_tests();
void run_convoy_ambush_system_tests();
void run_npc_dialogue_system_tests();
void run_station_monument_system_tests();
void run_information_propagation_system_tests();
void run_crew_activity_system_tests();
void run_visual_cue_system_tests();
void run_black_market_system_tests();
void run_price_history_system_tests();
void run_propaganda_system_tests();
void run_rest_station_system_tests();
void run_myth_boss_system_tests();
void run_ancient_tech_upgrade_system_tests();
void run_mod_manifest_system_tests();
void run_ancient_ai_remnant_system_tests();
void run_character_creation_screen_system_tests();
void run_view_mode_transition_system_tests();
void run_station_hangar_system_tests();
void run_tether_docking_system_tests();
void run_fps_spawn_system_tests();
void run_fps_character_controller_system_tests();
void run_interior_door_system_tests();
void run_eva_airlock_system_tests();
void run_fps_interaction_system_tests();
void run_fps_combat_system_tests();
void run_fps_inventory_system_tests();
void run_ship_interior_layout_system_tests();
void run_environmental_hazard_system_tests();
void run_fpsobjective_system_tests();
void run_wing_management_system_tests();
void run_economic_flow_system_tests();
void run_resource_production_chain_system_tests();
void run_fleet_doctrine_system_tests();
void run_player_progression_system_tests();
void run_terraforming_system_tests();
void run_food_processor_system_tests();
void run_fleet_squad_system_tests();
void run_cloaking_system_tests();
void run_jump_drive_system_tests();
void run_cargo_scan_system_tests();
void run_commander_disagreement_system_tests();
void run_imperfect_information_system_tests();
void run_captain_background_system_tests();
void run_rover_interior_system_tests();
void run_bike_garage_system_tests();
void run_visual_rig_system_tests();
void run_planetary_traversal_system_tests();
void run_solar_panel_system_tests();
void run_farming_deck_system_tests();
void run_docking_ring_extension_system_tests();
void run_rover_bay_ramp_system_tests();
void run_grid_construction_system_tests();
void run_misc_tests();
void run_dock_node_layout_tests();
void run_mission_consequence_tests();
void run_server_performance_monitor_tests();
void run_atlas_uipanel_tests();
void run_keyboard_navigation_tests();
void run_data_binding_tests();
void run_entity_stress_test_tests();
void run_rig_locker_tests();
void run_visual_coupling_tests();
void run_fpssalvage_path_tests();
void run_lavatory_interaction_tests();
void run_evaairlock_exit_tests();
void run_ancient_module_discovery_tests();
void run_client_prediction_system_tests();
void run_ship_template_mod_system_tests();
void run_database_persistence_system_tests();
void run_task_scheduler_system_tests();
void run_mod_manager_system_tests();
void run_ship_designer_system_tests();
void run_mission_editor_system_tests();
void run_content_validation_system_tests();
void run_cloud_deployment_config_system_tests();
void run_visual_feedback_queue_tests();
void run_mod_doc_generator_tests();
void run_community_content_repository_system_tests();
void run_pv_ptoggle_system_tests();
void run_dynamic_event_system_tests();
void run_fleet_morale_resolution_system_tests();
void run_persistence_delta_system_tests();
void run_outer_rim_logistics_distortion_system_tests();
void run_rumor_propagation_system_tests();
void run_galactic_response_curve_system_tests();
void run_ship_capability_rating_system_tests();
void run_module_cascading_failure_system_tests();
void run_navigation_bookmark_system_tests();
void run_fleet_supply_line_system_tests();
void run_crew_training_system_tests();
void run_asteroid_belt_system_tests();
void run_scan_probe_system_tests();
void run_autopilot_system_tests();
void run_jump_gate_system_tests();
void run_procedural_mission_generator_system_tests();
void run_incursion_system_tests();
void run_clone_bay_system_tests();
void run_loyalty_point_store_system_tests();

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "Nova Forge C++ Server System Tests" << std::endl;
    std::cout << "========================================" << std::endl;

    run_capacitor_system_tests();
    run_shield_recharge_system_tests();
    run_single_component_system_tests();
    run_state_machine_system_tests();
    run_weapon_system_tests();
    run_targeting_system_tests();
    run_ship_database_tests();
    run_wormhole_database_tests();
    run_wormhole_system_tests();
    run_fleet_system_tests();
    run_world_persistence_tests();
    run_movement_system_tests();
    run_logger_tests();
    run_server_metrics_tests();
    run_mission_system_tests();
    run_skill_system_tests();
    run_module_system_tests();
    run_inventory_system_tests();
    run_loot_system_tests();
    run_npc_database_tests();
    run_drone_system_tests();
    run_insurance_system_tests();
    run_bounty_system_tests();
    run_market_system_tests();
    run_corporation_system_tests();
    run_contract_system_tests();
    run_persistence_tests();
    run_pisystem_tests();
    run_manufacturing_system_tests();
    run_research_system_tests();
    run_chat_system_tests();
    run_character_creation_system_tests();
    run_tournament_system_tests();
    run_leaderboard_system_tests();
    run_station_system_tests();
    run_wreck_salvage_system_tests();
    run_server_console_tests();
    run_fleet_morale_system_tests();
    run_captain_personality_system_tests();
    run_fleet_chatter_system_tests();
    run_warp_anomaly_system_tests();
    run_captain_relationship_system_tests();
    run_emotional_arc_system_tests();
    run_fleet_cargo_system_tests();
    run_tactical_overlay_system_tests();
    run_combat_system_tests();
    run_ai_system_tests();
    run_warp_system_tests();
    run_mining_system_tests();
    run_ecs_components_tests();
    run_protocol_handler_tests();
    run_refining_system_tests();
    run_pcg_ship_generator_tests();
    run_fleet_formation_system_tests();
    run_captain_memory_system_tests();
    run_ship_fitting_system_tests();
    run_warp_cinematic_system_tests();
    run_anomaly_system_tests();
    run_scanner_system_tests();
    run_difficulty_scaling_system_tests();
    run_mission_template_system_tests();
    run_mission_generator_system_tests();
    run_reputation_system_tests();
    run_lod_system_tests();
    run_stress_test_tests();
    run_economy_tests();
    run_fleet_chatter_tests();
    run_captain_relationship_tests();
    run_rumor_propagation_tests();
    run_captain_personality_tests();
    run_persistence_stress_tests();
    run_spatial_hash_system_tests();
    run_compressed_persistence_tests();
    run_background_simulation_system_tests();
    run_npc_intent_system_tests();
    run_npc_behavior_tree_system_tests();
    run_combat_threat_system_tests();
    run_security_response_system_tests();
    run_ambient_traffic_system_tests();
    run_snapshot_replication_system_tests();
    run_interest_management_system_tests();
    run_pcg_framework_tests();
    run_character_mesh_cybernetics_tests();
    run_asteroid_field_generator_tests();
    run_anomaly_generator_tests();
    run_npc_encounter_generator_tests();
    run_warp_hudtravel_mode_tests();
    run_warp_auto_comfort_tests();
    run_warp_accessibility_tunnel_geometry_tests();
    run_phase_11_fleet_progression_system_tests();
    run_phase_11_fleet_cargo_ship_loss_tests();
    run_phase_11_station_deployment_system_tests();
    run_phase_11_fleet_warp_formation_system_tests();
    run_phase_11_fleet_civilization_tests();
    run_warp_meditation_system_tests();
    run_rumor_questline_system_tests();
    run_captain_departure_system_tests();
    run_captain_transfer_system_tests();
    run_npc_rerouting_system_tests();
    run_local_reputation_system_tests();
    run_station_news_system_tests();
    run_wreck_persistence_system_tests();
    run_fleet_history_system_tests();
    run_character_mesh_system_tests();
    run_rig_system_tests();
    run_turret_generator_tests();
    run_planet_generator_tests();
    run_habitat_generator_tests();
    run_grav_bike_tests();
    run_legend_system_tests();
    run_ancient_tech_tests();
    run_docking_system_tests();
    run_survival_system_tests();
    run_menu_system_tests();
    run_crew_system_tests();
    run_salvage_exploration_tests();
    run_interior_exterior_coupling_tests();
    run_race_and_lore_tests();
    run_market_order_tests();
    run_spine_hull_generator_tests();
    run_terrain_generator_tests();
    run_turret_placement_system_tests();
    run_damage_state_generator_tests();
    run_procedural_texture_generator_tests();
    run_economy_driven_generator_tests();
    run_ai_economic_actor_system_tests();
    run_turret_ai_system_tests();
    run_expanded_ship_class_tests();
    run_star_system_generator_tests();
    run_galaxy_generator_tests();
    run_alliance_system_tests();
    run_sovereignty_system_tests();
    run_war_declaration_system_tests();
    run_convoy_ambush_system_tests();
    run_npc_dialogue_system_tests();
    run_station_monument_system_tests();
    run_information_propagation_system_tests();
    run_crew_activity_system_tests();
    run_visual_cue_system_tests();
    run_black_market_system_tests();
    run_price_history_system_tests();
    run_propaganda_system_tests();
    run_rest_station_system_tests();
    run_myth_boss_system_tests();
    run_ancient_tech_upgrade_system_tests();
    run_mod_manifest_system_tests();
    run_ancient_ai_remnant_system_tests();
    run_character_creation_screen_system_tests();
    run_view_mode_transition_system_tests();
    run_station_hangar_system_tests();
    run_tether_docking_system_tests();
    run_fps_spawn_system_tests();
    run_fps_character_controller_system_tests();
    run_interior_door_system_tests();
    run_eva_airlock_system_tests();
    run_fps_interaction_system_tests();
    run_fps_combat_system_tests();
    run_fps_inventory_system_tests();
    run_ship_interior_layout_system_tests();
    run_environmental_hazard_system_tests();
    run_fpsobjective_system_tests();
    run_wing_management_system_tests();
    run_economic_flow_system_tests();
    run_resource_production_chain_system_tests();
    run_fleet_doctrine_system_tests();
    run_player_progression_system_tests();
    run_terraforming_system_tests();
    run_food_processor_system_tests();
    run_fleet_squad_system_tests();
    run_cloaking_system_tests();
    run_jump_drive_system_tests();
    run_cargo_scan_system_tests();
    run_commander_disagreement_system_tests();
    run_imperfect_information_system_tests();
    run_captain_background_system_tests();
    run_rover_interior_system_tests();
    run_bike_garage_system_tests();
    run_visual_rig_system_tests();
    run_planetary_traversal_system_tests();
    run_solar_panel_system_tests();
    run_farming_deck_system_tests();
    run_docking_ring_extension_system_tests();
    run_rover_bay_ramp_system_tests();
    run_grid_construction_system_tests();
    run_misc_tests();
    run_dock_node_layout_tests();
    run_mission_consequence_tests();
    run_server_performance_monitor_tests();
    run_atlas_uipanel_tests();
    run_keyboard_navigation_tests();
    run_data_binding_tests();
    run_entity_stress_test_tests();
    run_rig_locker_tests();
    run_visual_coupling_tests();
    run_fpssalvage_path_tests();
    run_lavatory_interaction_tests();
    run_evaairlock_exit_tests();
    run_ancient_module_discovery_tests();
    run_client_prediction_system_tests();
    run_ship_template_mod_system_tests();
    run_database_persistence_system_tests();
    run_task_scheduler_system_tests();
    run_mod_manager_system_tests();
    run_ship_designer_system_tests();
    run_mission_editor_system_tests();
    run_content_validation_system_tests();
    run_cloud_deployment_config_system_tests();
    run_visual_feedback_queue_tests();
    run_mod_doc_generator_tests();
    run_community_content_repository_system_tests();
    run_pv_ptoggle_system_tests();
    run_dynamic_event_system_tests();
    run_fleet_morale_resolution_system_tests();
    run_persistence_delta_system_tests();
    run_outer_rim_logistics_distortion_system_tests();
    run_rumor_propagation_system_tests();
    run_galactic_response_curve_system_tests();
    run_ship_capability_rating_system_tests();
    run_module_cascading_failure_system_tests();
    run_navigation_bookmark_system_tests();
    run_fleet_supply_line_system_tests();
    run_crew_training_system_tests();
    run_asteroid_belt_system_tests();
    run_scan_probe_system_tests();
    run_autopilot_system_tests();
    run_jump_gate_system_tests();
    run_procedural_mission_generator_system_tests();
    run_incursion_system_tests();
    run_clone_bay_system_tests();
    run_loyalty_point_store_system_tests();

    std::cout << "\n========================================" << std::endl;
    std::cout << "Results: " << testsPassed << "/" << testsRun << " tests passed" << std::endl;
    std::cout << "========================================" << std::endl;

    return (testsPassed == testsRun) ? 0 : 1;
}
